[package]
name = "jumprope"
version = "0.4.0"
authors = ["Joseph Gentle <me@josephg.com>"]
edition = "2018"
description = "Simple, fast rope (fancy string) library built on top of Skiplists"
resolver = "2"
repository = "https://github.com/josephg/jumprope-rs"
license = "ISC OR Apache-2.0"

[workspace]
members = ["jumprope-wasm", "bench"]

[features]
default = ["ddos_protection"]
ddos_protection = []

[dependencies]
rand = { version = "0.8", features = ["small_rng"] }

# This is just used for a couple functions. TODO: Probably better to inline them locally.
ropey = "1.3.1"


[profile.release]
lto = true
codegen-units = 1

[profile.release.package.jumprope-wasm]
#opt-level = "s"
opt-level = 2
